"""teste

Revision ID: 05727002a1c2
Revises: 15a1175eba5b
Create Date: 2026-06-17 19:03:17.833811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05727002a1c2'
down_revision = '15a1175eba5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desempenho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('periodo1', sa.Text(), nullable=True),
    sa.Column('periodo2', sa.Text(), nullable=True),
    sa.Column('periodo3', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desempenho')
    # ### end Alembic commands ###
