"""create alunos

Revision ID: 095c25225ae7
Revises: 
Create Date: 2026-05-29 10:02:52.542329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095c25225ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.Text(), nullable=False),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('nome_pai1', sa.Text(), nullable=True),
    sa.Column('nome_pai2', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('sala', sa.Text(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    # ### end Alembic commands ###
