"""teste

Revision ID: 15a1175eba5b
Revises: 282e811cbbf5
Create Date: 2026-06-17 19:00:28.190334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a1175eba5b'
down_revision = '282e811cbbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desempenho')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desempenho',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('periodo1', sa.TEXT(), nullable=True),
    sa.Column('periodo2', sa.TEXT(), nullable=True),
    sa.Column('periodo3', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
