"""add competencias

Revision ID: 591b3f1d7373
Revises: 
Create Date: 2026-06-11 12:34:25.577026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591b3f1d7373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.Text(), nullable=False),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('nome_pai1', sa.Text(), nullable=True),
    sa.Column('nome_pai2', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('salas',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('turno', sa.Text(), nullable=False),
    sa.Column('horario_inicio', sa.Text(), nullable=True),
    sa.Column('horario_termino', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('competencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.pid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sala_alunos',
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.pid'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.sid'], ),
    sa.PrimaryKeyConstraint('sala_id', 'aluno_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sala_alunos')
    op.drop_table('competencias')
    op.drop_table('salas')
    op.drop_table('alunos')
    # ### end Alembic commands ###
