"""atualizao model alunos

Revision ID: 9cb9238eed56
Revises: dfb2177a06da
Create Date: 2026-06-17 12:48:19.950782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb9238eed56'
down_revision = 'dfb2177a06da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_column('notas')

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
